# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

java_version=21

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependency Versions
neo_version=21.1.228
yacl_version=3.8.1+1.21.1-neoforge

# Loader Ranges
minecraft_version_range=[1.21.1,1.22)
sodium_version_range=[0.6.13+mc1.21.1,0.9)
iris_version_range=[1.8.12+mc1.21.1,2.0)
loader_version_range=[1,)

## Mod Properties
mod_id=where_winds_blow
mod_name=Where Winds Blow
mod_authors=jvn
mod_license=All Rights Reserved
mod_version=1.0.0-pre-release.7
maven_group=com.jvn.wherewindsblow
archives_base_name=where_winds_blow
mod_description=I'd go with you.
mod_display_url=https://github.com/JevenDev/Where-Winds-Blow
mod_issue_tracker=https://github.com/JevenDev/Where-Winds-Blow/issues
